### PR TITLE
Add / Delete / List contestants on admin page

### LINKED ISSUE #7: admin crud contestant

### PR DESCRIPTION
**Pull request by kangkyu**
closes #7

### CODE REVIEW

**Comment by software-engr-full-stack** [comment]
Please bump ruby version to at least 3. Version 3.0.4 is what's being used in the master branch.

**Review by software-engr-full-stack — COMMENTED** [review]
Please bump ruby version to at least 3 in the Gemfile. Version 3.0.4 is what's being used in the master branch.

**Review by software-engr-full-stack — APPROVED** [review]
Please bump ruby version to at least 3 in the Gemfile. Version 3.0.4 is what's being used in the master branch.

**Comment by kangkyu** [comment]
Thank you @software-engr-full-stack

**Pull request merged**
